# Generated by Django 5.0 on 2023-12-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='income',
            name='slug',
            field=models.SlugField(),
        ),
    ]
