# Generated by Django 5.0 on 2023-12-21 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_expense_slug_alter_income_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='income',
            name='slug',
        ),
    ]
